### ISSUE TITLE
External Mqtt not working in 2.4.20

### ISSUE THREAD

**Issue by peteh** [rhasspy/rhasspy#279]
I wanted to add another satellite to my setup andI tried to configure an external mqtt server that is running on another machine. 
I setup Raspberry OS 64bit with docker completely from scratch and I think I followed the instructions for rhasspy correctly. 
However, the error message in docker logs is 
```
ERROR:HermesMqtt:connecting
Traceback (most recent call last):
  File "/usr/share/rhasspy/rhasspy/mqtt.py", line 126, in do_connect
    ret = self.client.connect(self.host, self.port)
AttributeError: 'NoneType' object has no attribute 'connect'
DEBUG:HermesMqtt:Reconnecting in 5 second(s).
```
It seems like the client object is None for some reason. Maybe something wrong with reading the config? 
These are my mqtt settings: 
![image](https://user-images.githubusercontent.com/918728/161154294-8783cc9a-f51b-4c8d-a551-1cd90600d356.png)

It works with an older 2.5.11 that is running on another machine. 

Thanks for putting all the work into it. I'm using it pretty reliably for a few months now.

**Comment by peteh** [comment]
Nevermind, I was using the tutorial for clients and servers which uses outdated docker images.
